### ISSUE TITLE
[Question] RFCOMM

### ISSUE THREAD

**Issue by manio** [JojiiOfficial/bluetooth-serial-port-async#3]
Hi Jojii,
Please tell me one thing. I can see that in current linux stack the `rfcomm` utility is [deprecated](https://www.reddit.com/r/archlinux/comments/7o5c3m/how_can_i_use_a_serial_communication_via_bluetooth/).
In some distros (_Arch_) one can still install eg [bluez-deprecated-tools](https://archlinux.org/packages/extra/x86_64/bluez-deprecated-tools/), while eg in _Debian_ or _Raspberry Pi OS_ it is still there but I think it is just a matter of time.

I need to communicate using RFCOMM with my bluetooth OBD dongle to connect to my electric car (imported from your country, btw ;))
So far I was using `rfcomm` + `socat` utility on the raspberry pi and on server I was running regular x86 rust app using [tokio::net::TcpStream](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html).

Today I switched to your crate (it was quite easy as your `UnixSocket` was almost a drop-in replacement for `TcpStream`) and I successfully crosscompiled the binary (I had to prior copy `libbluetooth.a` from raspberry to `/usr/aarch64-linux-gnu/lib` to be able to crosscompile it).

It is communicating as before, but I am really happy with this as I got rid of two additional utilities (rfcomm and socat) and I can directly use the BT dongle on the pi using your crate! :)

Am I right, that using your lib is the right choice for the future (I mean it is not using some deprecated API as `rfcomm` tool)?

**Comment by JojiiOfficial** [comment]
Hey
I don't see any reason that this repo will become deprecated. However this is just a fork of https://github.com/Dushistov/bluetooth-serial-port to make it work with async rust.
I don't really use it anymore and thus am not maintaining it actively.
The "original" repository, I forked it from (which is also just a fork btw) doesn't seem to be actively maintained either. 
If you need it to work with async code and you don't care having to fix issues you may encounter yourself, this repo might be a good choice (although I don't know if there is a new, better library that might work better)

**Comment by manio** [comment]
Thanks for explanation, closing.
